package com.dbs.ordermatching.utils;

public class DBInit {
	public static String CUSTODIANS="[\r\n"
			+ "        {\r\n"
			+ "            \"custodianname\": \"BNP Paribas Securities ServicesFrance\",\r\n"
			+ "            \"custodianid\": \"CS001\",\r\n"
			+ "            \"password\": \"password\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"custodianname\": \"The Bank of New York Mellon CorporationU.S.\",\r\n"
			+ "            \"custodianid\": \"CS002\",\r\n"
			+ "            \"password\": \"password\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"custodianname\": \"EuroclearBelgium\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"password\": \"password\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"custodianname\": \"HSBC Securities ServicesUnited Kingdom\",\r\n"
			+ "            \"custodianid\": \"CS004\",\r\n"
			+ "            \"password\": \"password\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"custodianname\": \"Credit SuisseSwitzerland\",\r\n"
			+ "            \"custodianid\": \"CS005\",\r\n"
			+ "            \"password\": \"password\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"custodianname\": \"Northern Trust CorporationU.S.\",\r\n"
			+ "            \"custodianid\": \"CS006\",\r\n"
			+ "            \"password\": \"password\"\r\n"
			+ "        }\r\n"
			+ "    ]";
	
	public static String CLIENTSJSON = "[\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS001\",\r\n"
			+ "            \"clientname\": \"MACQUARIE BANK LIMITED\",\r\n"
			+ "            \"custodianid\": \"CS001\",\r\n"
			+ "            \"transactionlimit\": \"14000000\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS002\",\r\n"
			+ "            \"clientname\": \"LLOYDS BANK CORPORATE MARKETS PLC\",\r\n"
			+ "            \"custodianid\": \"CS001\",\r\n"
			+ "            \"transactionlimit\": \"14000000\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS003\",\r\n"
			+ "            \"clientname\": \"KEYBANK NATIONAL ASSOCIATION\",\r\n"
			+ "            \"custodianid\": \"CS001\",\r\n"
			+ "            \"transactionlimit\": \"18000000\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS004\",\r\n"
			+ "            \"clientname\": \"JP MORGAN SECURITIES LLC\",\r\n"
			+ "            \"custodianid\": \"CS001\",\r\n"
			+ "            \"transactionlimit\": \"5000000\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS005\",\r\n"
			+ "            \"clientname\": \"JEFFERIES FINANCIAL SERVICES, INC.\",\r\n"
			+ "            \"custodianid\": \"CS002\",\r\n"
			+ "            \"transactionlimit\": \"21000006\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS006\",\r\n"
			+ "            \"clientname\": \"JB DRAX HONORE UK LTD\",\r\n"
			+ "            \"custodianid\": \"CS002\",\r\n"
			+ "            \"transactionlimit\": \"21000006\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS007\",\r\n"
			+ "            \"clientname\": \"J ARON & COMPANY SINGAPORE PTE\",\r\n"
			+ "            \"custodianid\": \"CS002\",\r\n"
			+ "            \"transactionlimit\": \"18000006\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS008\",\r\n"
			+ "            \"clientname\": \"J ARON & COMPANY LLC\",\r\n"
			+ "            \"custodianid\": \"CS002\",\r\n"
			+ "            \"transactionlimit\": \"7500003\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS009\",\r\n"
			+ "            \"clientname\": \"INTESA SANPAOLO SPA\",\r\n"
			+ "            \"custodianid\": \"CS002\",\r\n"
			+ "            \"transactionlimit\": \"21000012\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS010\",\r\n"
			+ "            \"clientname\": \"ING CAPITAL MARKETS LLC\",\r\n"
			+ "            \"custodianid\": \"CS002\",\r\n"
			+ "            \"transactionlimit\": \"21000012\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS011\",\r\n"
			+ "            \"clientname\": \"ICBC STANDARD BANK PLC\",\r\n"
			+ "            \"custodianid\": \"CS002\",\r\n"
			+ "            \"transactionlimit\": \"18000012\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS012\",\r\n"
			+ "            \"clientname\": \"HSBC BANK USA NA\",\r\n"
			+ "            \"custodianid\": \"CS002\",\r\n"
			+ "            \"transactionlimit\": \"5000004\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS013\",\r\n"
			+ "            \"clientname\": \"HSBC BANK PLC\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"17500015\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS014\",\r\n"
			+ "            \"clientname\": \"GOLDMAN SACHS PARIS INC ET CIE\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"28000024\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS015\",\r\n"
			+ "            \"clientname\": \"GOLDMAN SACHS MEXICO CASA DE BOLSA SA DE CV\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"12000012\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS016\",\r\n"
			+ "            \"clientname\": \"GAIN GTX LLC\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"12500015\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS017\",\r\n"
			+ "            \"clientname\": \"FIFTH THIRD BANK NATIONAL ASSOCIATION\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"7000008\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS018\",\r\n"
			+ "            \"clientname\": \"ED&F MAN DERIVATIVE PRODUCTS INC\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"28000032\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS019\",\r\n"
			+ "            \"clientname\": \"DEUTSCHE BANK AG\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"12000016\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS020\",\r\n"
			+ "            \"clientname\": \"DARBY SWAP TRADING LLC\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"7500012\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS021\",\r\n"
			+ "            \"clientname\": \"DANSKE BANK AS\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"21000030\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS022\",\r\n"
			+ "            \"clientname\": \"CREDIT SUISSE SECURITIES EUROPE LIMITED\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"35000050\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS023\",\r\n"
			+ "            \"clientname\": \"COOPERATIEVE RABOBANK UA\",\r\n"
			+ "            \"custodianid\": \"CS003\",\r\n"
			+ "            \"transactionlimit\": \"12000020\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS024\",\r\n"
			+ "            \"clientname\": \"COMMONWEALTH BANK OF AUSTRALIA\",\r\n"
			+ "            \"custodianid\": \"CS004\",\r\n"
			+ "            \"transactionlimit\": \"7500015\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS025\",\r\n"
			+ "            \"clientname\": \"CITIGROUP ENERGY INC\",\r\n"
			+ "            \"custodianid\": \"CS004\",\r\n"
			+ "            \"transactionlimit\": \"21000036\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS026\",\r\n"
			+ "            \"clientname\": \"CITIBANK N A\",\r\n"
			+ "            \"custodianid\": \"CS004\",\r\n"
			+ "            \"transactionlimit\": \"14000024\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS027\",\r\n"
			+ "            \"clientname\": \"CITADEL SECURITIES SWAP DEALER LLC\",\r\n"
			+ "            \"custodianid\": \"CS004\",\r\n"
			+ "            \"transactionlimit\": \"36000072\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS028\",\r\n"
			+ "            \"clientname\": \"CARGILL INCORPORATED\",\r\n"
			+ "            \"custodianid\": \"CS005\",\r\n"
			+ "            \"transactionlimit\": \"10000024\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS029\",\r\n"
			+ "            \"clientname\": \"CAPITAL ONE NATIONAL ASSOCIATION\",\r\n"
			+ "            \"custodianid\": \"CS005\",\r\n"
			+ "            \"transactionlimit\": \"10500021\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS030\",\r\n"
			+ "            \"clientname\": \"CANTOR FITZGERALD SECURITIES\",\r\n"
			+ "            \"custodianid\": \"CS005\",\r\n"
			+ "            \"transactionlimit\": \"21000042\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS031\",\r\n"
			+ "            \"clientname\": \"CANADIAN IMPERIAL BANK OF COMMERCE\",\r\n"
			+ "            \"custodianid\": \"CS005\",\r\n"
			+ "            \"transactionlimit\": \"12000028\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS032\",\r\n"
			+ "            \"clientname\": \"BP ENERGY COMPANY\",\r\n"
			+ "            \"custodianid\": \"CS006\",\r\n"
			+ "            \"transactionlimit\": \"7500021\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"clientid\": \"DBS033\",\r\n"
			+ "            \"clientname\": \"BOFA SECURITIES JAPAN CO LTD\",\r\n"
			+ "            \"custodianid\": \"CS006\",\r\n"
			+ "            \"transactionlimit\": \"1500000\",\r\n"
			+ "            \"balance\": \"1234532.00\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "";

	public static String INSTRUMENTSJSON = "[\r\n"
			+ "        {\r\n"
			+ "            \"instrumentid\": \"I001\",\r\n"
			+ "            \"instrumentname\": \"US treasury Bills\",\r\n"
			+ "            \"facevalue\": \"100\",\r\n"
			+ "            \"expiry\": \"2021-09-18\",\r\n"
			+ "            \"minquanity\": \"25\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"instrumentid\": \"I002\",\r\n"
			+ "            \"instrumentname\": \"RBI-2026 -6.5%\",\r\n"
			+ "            \"facevalue\": \"1000\",\r\n"
			+ "            \"expiry\": \"2021-09-26\",\r\n"
			+ "            \"minquanity\": \"25\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"instrumentid\": \"I003\",\r\n"
			+ "            \"instrumentname\": \"RBI-2045 -8%\",\r\n"
			+ "            \"facevalue\": \"1000\",\r\n"
			+ "            \"expiry\": \"2021-09-26\",\r\n"
			+ "            \"minquanity\": \"25\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"instrumentid\": \"I004\",\r\n"
			+ "            \"instrumentname\": \"USDINR\",\r\n"
			+ "            \"expiry\": \"2021-09-26\",\r\n"
			+ "            \"minquanity\": \"25\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"instrumentid\": \"I005\",\r\n"
			+ "            \"instrumentname\": \"EUR USD-FUT\",\r\n"
			+ "            \"expiry\": \"2021-09-26\",\r\n"
			+ "            \"minquanity\": \"25\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "";
	public static boolean BUILD_DB = true;
}
